import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css'; // Add this line
import "./globals.css";
import MenuBarHeader from "@/component/MenuBarHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* HEADER MENU */}
        <MenuBarHeader />

        {/* CONTENT BODY */}
        <div className="container-fluid" style={{minHeight: '100vh'}}>
            {children}
        </div>
      </body>
    </html>
  );
}
